// packages/frontend/src/components/PhotosBulkActions.vue
<script setup lang="ts">
import { Images } from '../../../shared/src';
import { IAlbum } from '../../../shared/src/models';
import { downloadPhotos } from '../api';
import Button from './Button.vue';
import { useMutation, useQuery } from '@tanstack/vue-query';
import { ref } from "vue"
import Dialog from './Dialog.vue';
import { getUserAlbums } from '../api/albums';
import { addPhotosToAlbum } from '../api/album-photos'
const props = defineProps<{ selectedPhotos: Images }>()

// const albums: IAlbum[] = [{
//     creationDate: new Date(),
//     name: "album 1",
//     id: "1"
// },
// {
//     creationDate: new Date(),
//     name: "album 2",
//     id: "21"
// }]

const { data: albums } = useQuery({
    queryKey: ["albums"],
    queryFn: getUserAlbums,
})

const { mutate } = useMutation({
    mutationFn: addPhotosToAlbum
})

const addPhotosToAlbumFn = (album: IAlbum) => mutate({ album, photos: props.selectedPhotos })


const emit = defineEmits<{ (e: 'photosDownloaded'): void, (e: 'unselectClicked'): void }>()


const { isLoading, mutate: downLoadPhotosFn } = useMutation({
    mutationFn: async () => {
        await downloadPhotos(props.selectedPhotos)
        emit("photosDownloaded")
    },

})

const emitUnselectClicked = () => emit('unselectClicked')

const dialogOpen = ref(false)




</script>

<template>
    <div class="flex flex-grow">
        <div class="flex items-center font-medium text-2xl text-fuchsia-800 gap-4">
            <div>{{ selectedPhotos.length }} selected</div>
            <Button size="sm" @click="emitUnselectClicked">Unselect</Button>


        </div>
        <div class="flex justify-end flex-grow items-center gap-4">
            <Button :style="'flat'" :round="true" @click.prevent="() => dialogOpen = true">+</Button>


            <Dialog v-model:open="dialogOpen">
                <template #header>
                    Add to album
                </template>

                <div class="flex flex-col gap-2 max-h-96 overflow-auto">
                    <div @click="() => addPhotosToAlbumFn(album)" v-for="album of albums"
                        class="text-gray-800 px-4 py-2 w-80 hover:bg-pink-200 cursor-pointer">
                        {{ album.name }}</div>
                </div>
            </Dialog>
            <Button :style="'flat'" @click="() => downLoadPhotosFn()" :is-loading="isLoading">Download</Button>
        </div>
    </div>
</template>

// webapp/components/photos-bulk-actions.tsx
import {
  DropdownOptionCmp,
  Button,
  Dropdown,
  DialogUI,
  DialogTitle,
} from "./ui";
import { useState } from "react";
import Image from "next/image";
import { CreateAlbumDialog } from "./create-album/create-album-dialog";
import { Photos } from "../core/features/photos";
import { Album, useGetAllAlbumsQuery } from "../core/features/albums";
import { addPhotosToAlbum } from "../core/features/album-photos";
import { IconButton } from "./ui/icon-button";

export const PhotosBulkActions = ({
  selectedPhotos,
  onClearClick,
  unSelectPhotos,
}: {
  selectedPhotos: Photos;
  onClearClick: () => void;
  unSelectPhotos: () => void;
}) => {
  const { data } = useGetAllAlbumsQuery();
  const albums = data || [];
  const [addToAlbumDialogOpen, setAddToAlbumDialogOpen] = useState(false);
  const [createAlbumDialogOpen, setCreateAlbumDialogOpen] = useState(false);
  const trigger = <IconButton icon="plus"></IconButton>;

  const closeAddToAlbumDialog = () => setAddToAlbumDialogOpen(false);

  return (
    <div className="px-2 flex flex-grow  items-center gap-4 text-fuchsia-600">
      <div> {selectedPhotos.length} selected</div>

      <Button style="simple" onClick={onClearClick}>
        Clear
      </Button>

      <div className="flex flex-grow justify-end">
        <Dropdown trigger={trigger}>
          <DropdownOptionCmp onClick={() => setAddToAlbumDialogOpen(true)}>
            Add to album
          </DropdownOptionCmp>
          <DropdownOptionCmp onClick={() => setCreateAlbumDialogOpen(true)}>
            Create album
          </DropdownOptionCmp>
        </Dropdown>
      </div>
      <AddPhotosToAlbumDialog
        open={addToAlbumDialogOpen}
        close={closeAddToAlbumDialog}
        albums={albums}
        onAlbumClick={(album) => {
          addPhotosToAlbum({ album, photos: selectedPhotos });
          closeAddToAlbumDialog();
          unSelectPhotos();
        }}
      />

      <CreateAlbumDialog
        open={createAlbumDialogOpen}
        closeDialog={() => setCreateAlbumDialogOpen(false)}
        selectedPhotos={selectedPhotos}
        onAlbumCreated={unSelectPhotos}
      />
    </div>
  );
};

export const AddPhotosToAlbumDialog = ({
  open,
  close,
  albums,
  onAlbumClick,
}: {
  albums: Album[];
  open: boolean;
  close: () => void;
  onAlbumClick: (album: Album) => void;
}) => {
  return (
    <DialogUI
      open={open}
      close={close}
      title={
        <DialogTitle>
          <div className="px-4">Add to</div>
        </DialogTitle>
      }
    >
      <div className="flex flex-col items-start gap-1">
        {albums.map((a) => (
          <div
            key={a.id}
            className="flex gap-3 items-center flex-grow w-full px-4 py-3 hover:bg-pink-50 cursor-pointer"
            onClick={() => onAlbumClick(a)}
          >
            <Image
              src={a.coverPhoto}
              alt={a.name}
              height={40}
              width={40}
              className="h-10 w-10"
            />
            <div className="font-semibold text-sm text-gray-700">{a.name}</div>
          </div>
        ))}
      </div>
    </DialogUI>
  );
};
