// webapp/components/full-screen-photo-gallery/full-screen-photo-gallery.tsx
/* eslint-disable @next/next/no-img-element */
import {
  ArrowLeftCircleIcon,
  ArrowLeftIcon,
  ArrowRightCircleIcon,
} from "@heroicons/react/20/solid";
import { DialogUI } from "../shared";
import { Photos, Photo } from "../../core/photos";
import {
  getNextPhoto,
  getPreviousPhoto,
} from "../photos-list/previous-next-photo";

export const FullScreenPhotoGallery = ({
  fullScreenPhoto,
  setFullScreenPhoto,
  allPhotos,
  open,
  close,
}: {
  fullScreenPhoto: Photo | undefined;
  setFullScreenPhoto: (photo: Photo) => void;
  allPhotos: Photos;
  open: boolean;
  close: () => void;
}) => {
  const moveToPreviousPhoto = () => {
    if (!fullScreenPhoto) return;

    const previousPhoto = getPreviousPhoto({
      allPhotos,
      currentPhoto: fullScreenPhoto,
    });
    setFullScreenPhoto(previousPhoto);
  };

  const moveToNextPhoto = () => {
    if (!fullScreenPhoto) return;

    const previousPhoto = getNextPhoto({
      allPhotos,
      currentPhoto: fullScreenPhoto,
    });
    setFullScreenPhoto(previousPhoto);
  };

  return (
    <DialogUI open={open} close={close} title="" fullScreen={true} color="dark">
      <div className="flex flex-col relative w-full h-full items-center justify-center">
        <img
          src={fullScreenPhoto?.url || ""}
          alt="photo"
          className="max-h-full max-w-full"
        />

        <div className="absolute top-0 w-full h-10 items-center px-2 py-1 ">
          <div
            className="rounded-full p-1 cursor-pointer hover:bg-fuchsia-800 w-fit h-fit"
            onClick={close}
          >
            <ArrowLeftIcon className="h-6 w-6" color="white" />
          </div>
        </div>

        <div className="absolute top-1/3 bottom-1/3 left-0 right-0 flex items-center justify-between px-3  ">
          <div className="h-full group w-1/2 flex items-center">
            <div
              className="rounded-full p-1 cursor-pointer w-fit h-fit invisible group-hover:visible"
              onClick={moveToPreviousPhoto}
            >
              <ArrowLeftCircleIcon className="h-12 w-12" color="white" />
            </div>
          </div>

          <div className="h-full group w-1/2 flex items-center justify-end">
            <div
              className="rounded-full p-1 cursor-pointer w-fit h-fit invisible group-hover:visible"
              onClick={moveToNextPhoto}
            >
              <ArrowRightCircleIcon className="h-12 w-12" color="white" />
            </div>
          </div>
        </div>
      </div>
    </DialogUI>
  );
};

// packages/frontend/src/components/FullScreenPhotoGallery.vue
<script setup lang="ts">
import { Image, UserImages } from '@shared';
import { reactive } from 'vue';
import { watch } from 'vue';
import { PhotosGallery } from '../utils/photos-gallery';
import { computed } from 'vue';
import { ref } from 'vue';
import { ICONS } from '../utils/icons';



const props = defineProps<{ userPhotos: UserImages }>()


const photosGallery = reactive(new PhotosGallery([]))

watch(props, () => {
    photosGallery.setUserPhotos(props.userPhotos || [])
})

const dialogOpen = ref(false)


const openDialog = () => dialogOpen.value = true
const closeDialog = () => dialogOpen.value = false
const openGalleryWithPhoto = (photo: Image) => {
    photosGallery.showPhoto(photo);
    openDialog()
}

const previousPhoto = () => photosGallery.goToPreviousPhoto()
const nextPhoto = () => photosGallery.gotoNextPhoto()



defineExpose({ openGalleryWithPhoto })
</script>

<template>
    <v-dialog v-model="dialogOpen" fullscreen :scrim="false" transition="dialog-bottom-transition"
        class="bg-black text-white relative p-2 ">

        <div @click="closeDialog"
            class="cursor-pointer absolute left-4 top-4 p-1 rounded-full h-8 w-8 hover:bg-fuchsia-300 text-white flex justify-center items-center">
            <img :src="ICONS.ARROW_LEFT" />
        </div>

        <div class="absolute left-0 right-0 px-3 top-1/3 bottom-1/3 flex items-center justify-between  ">



            <div @click="previousPhoto" v-if="photosGallery.hasPreviousPhoto()"
                class="cursor-pointer w-12 h-12 rounded-full bg-fuchsia-200 hover:bg-fuchsia-300 text-white flex items-center justify-center text-lg">
                <img :src="ICONS.ARROW_LEFT_GRAY" />
            </div>

            <div class="flex flex-grow justify-end items-center">
                <div @click="nextPhoto" v-if="photosGallery.hasNextPhoto()"
                    class="cursor-pointer w-12 h-12 rounded-full bg-fuchsia-200 hover:bg-fuchsia-300 text-white flex items-center justify-center text-lg">
                    <img :src="ICONS.ARROW_RIGHT_GRAY" />
                </div>
            </div>
        </div>
        <div class="flex w-full h-full items-center justify-center">
            <img :src="photosGallery.currentPhoto?.url" class="max-h-full w-auto object-contain" />

        </div>

    </v-dialog>
</template>
