// webapp/components/layout/side-nav.tsx
import Link from "next/link";

export function SideNav() {
  return (
    <div className="w-64">
      <div className="flex flex-col h-full gap-4 py-6 px-8 bg-pink-300 text-white text-2xl font-bold">
        <Link href={"/"}>Photos</Link>
        <Link href={"/albums"}>Albums</Link>
      </div>
    </div>
  );
}

// packages/frontend/src/components/SideNav.vue
<script setup lang="ts">

</script>

<template >
    <div class="flex-shrink-0 flex flex-grow-0 flex-col gap-4 py-4  bg-fuchsia-700 " style="flex-basis: 200px;">


        <router-link to="/"
            class="text-xl  text-white w-full hover:bg-fuchsia-800 p-2 px-4 border-r-2 border-transparent hover:border-black">Photos</router-link>
        <router-link to="/albums"
            class="text-xl  text-white w-full hover:bg-fuchsia-800 p-2 px-4 border-r-2 border-transparent hover:border-black">Albums</router-link>

    </div>
</template>
